name: Deploy main & test builds

on:
  push:
    branches: [main, ci]

jobs:
  deploy:
    name: Deploy main tag image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip') && !contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ghcr.io/mu-editor/mu-appimage:main .
      - name: Push master tag to ghcr.io
        run: docker push ghcr.io/mu-editor/mu-appimage:main

  build-mu-appimage:
    name: Build Mu AppImage with main tag image
    needs: deploy
    runs-on: ubuntu-latest
    container: ghcr.io/mu-editor/mu-appimage:main
    steps:
      - name: Check Versions
        run: |
          uname -a
          python -c "import sys; print(sys.version)"
          python -c "import platform, struct; print(platform.machine(), struct.calcsize('P') * 8)"
          python -c "import sys; print(sys.executable)"
          python -m pip --version
          pip --version
          pip list --verbose
      - name: Clone Mu
        run: |
          git clone https://github.com/mu-editor/mu.git
          cd mu
          git checkout -b docker-appimage origin/docker-appimage
      - name: Install Mu test dependencies
        run: |
          cd mu
          pip install .[tests]
          pip list
      - name: Build Mu AppImage
        run: |
          cd mu
          xvfb-run make linux
